In [261]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing, neighbors
import pandas as pd
from sklearn.utils import shuffle
import csv

NameError: name 'sys' is not defined

In [227]:
with open('/home/cot12/Documents/ddsm/ddsm-graphs-and-csvs/ddsm_cut-fe.csv') as csvfile:   # open csv file
    readcsv = csv.reader(csvfile, delimiter = ',')# read file 
    density_features = []
    for row in readcsv:
        densitys_f = row[2]
        density_features.append(densitys_f)
        
    density_features [0] = '0' # ignore first elememt of list
    density_features.pop(0)
features = np.array(density_features,dtype=np.float)

In [228]:
with open('/home/cot12/Documents/ddsm/ddsm-graphs-and-csvs/ddsm_cut-fe.csv') as csvfile:   # open csv file
    readcsv = csv.reader(csvfile, delimiter = ',')# read file 
    density = []
    for row in readcsv:
        dense = row[1]
        density.append(dense)
        
    density[0] = '0' # ignore first elememt of list
    density.pop(0)
densities = np.array(density, dtype = np.int)

In [264]:
combined_array = np.zeros((densities.shape[0],2))
combined_array[:,0] = features
combined_array[:,1] = densities
np.random.shuffle(combined_array)
full_array = combined_array
print(full_array)
    

[[0.69694726 3.        ]
 [0.58565544 3.        ]
 [0.64584752 4.        ]
 ...
 [0.75275114 2.        ]
 [0.74486683 2.        ]
 [0.61080131 4.        ]]


In [280]:
def sets(m):
    count = 0
    X_test_set = np.zeros((80,1)) #not desntiy
    Y_test_set = np.zeros((80,1))
    Y_train_set = np.zeros((720,1))
    for i in range(0,10):
        if i == m:
            X_test_set = full_array[(i*80):((i+1)*80),0]
            Y_test_set = full_array[(i*80):((i+1)*80),1]
        else:
            X_train_set[count*80:((count+1)*80),0] = full_array[(i*80):((i+1)*80),0]
            Y_train_set[count*80:((count+1)*80),0] = full_array[(i*80):((i+1)*80),1]
            count +=1
    return X_test_set, Y_test_set, X_train_set, Y_train_set

In [281]:
sets(1)

(array([0.5931148 , 0.60803152, 0.69381954, 0.59394712, 0.74868676,
        0.78964176, 0.64726769, 0.60519191, 0.78309536, 0.64641469,
        0.74315167, 0.66216567, 0.69293472, 0.81553974, 0.64132551,
        0.68486995, 0.68096579, 0.76925346, 0.79031117, 0.71866783,
        0.71758726, 0.65461728, 0.69126966, 0.71576176, 0.63703546,
        0.61725493, 0.79475623, 0.76512138, 0.59498302, 0.59875541,
        0.69012742, 0.5395832 , 0.77511951, 0.6321933 , 0.78520084,
        0.59352836, 0.76793868, 0.61183253, 0.61501107, 0.76884411,
        0.61514416, 0.69094711, 0.72913967, 0.61909813, 0.7550182 ,
        0.77926637, 0.65284577, 0.59573687, 0.59896162, 0.73941637,
        0.62044875, 0.71355467, 0.74307682, 0.80840568, 0.75183353,
        0.70216899, 0.64545666, 0.64560502, 0.77523542, 0.64062512,
        0.76790749, 0.611095  , 0.59224326, 0.7611695 , 0.64579828,
        0.7211716 , 0.68942529, 0.79835688, 0.71658105, 0.76118427,
        0.61449369, 0.7513861 , 0.7942399 , 0.74

In [44]:
combined_array = np.zeros(densities.shape[0],2)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.1)

clf = neighbors.KNeighborsClassifier()

In [45]:
clf.fit(X_train, Y_train)
accuracy = clf.score(X_test, Y_test)
print(accuracy)
 split_array[:,i] = combined_array[(i*80):((i+1)*80),0]

0.34523809523809523


In [230]:
split_array[:,(i+10)] = combined_array[(i*80):((i+1)*80),1]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
